
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import FirstMenu from '@/components/Manu/FirstMenu'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Thynne',
  description: 'Generated by create next app',
}

export default function RootLayout({  children, }: {  children: React.ReactNode }) {

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="favicon.ico" sizes="any" />
      </head>
      <body className={inter.className}>
        <FirstMenu />
        {children}

      </body>
    </html>
  )
}
